docs: add block.json section
wpmetabox/docsv2 pull request #176
Opened 2024-04-11 08:58 UTC by tanftw

Also:

- Remove `anchor` since it isn't supported

2024-04-11 10:23 UTC, rilwis requested changes
A có check với Grammarly và update 1 chút.

Em update lại giúp a phần dữ liệu trong `$attributes` và dữ liệu raw trong `$attributes['data']` nhé: trong các phần về render trước chứ ko chỉ trong phần về `block.json`.

2024-04-12 09:33 UTC, tanftw commented
E mới thêm rồi nhé.

2024-04-12 10:08 UTC, rilwis approved these changes

2024-04-17 03:10 UTC, rilwis approved these changes

2024-04-17 03:10 UTC, merged