fix: taxonomy is not cloneable
wpmetabox/docsv2 pull request #217
Opened 2024-08-16 08:46 UTC by tanftw

2024-08-16 09:26 UTC, rilwis requested changes

2024-08-16 09:26 UTC, rilwis commented on docs/fields/taxonomy-advanced.md
> -If the field is cloneable, then the value is stored as a serialized array in a single row in the database.
Field `taxonomy_advanced` vẫn lưu giá trị ở dạng serialized array chứ e nhỉ?

2024-08-16 09:31 UTC, tanftw commented on docs/fields/taxonomy-advanced.md
> -If the field is cloneable, then the value is stored as a serialized array in a single row in the database.
Field này multiple thì sẽ lưu dạng csv a ạ, đoạn dưới nhắc đến cloneable mà mình không support.

2024-08-19 04:41 UTC, rilwis commented on docs/fields/taxonomy-advanced.md
> -If the field is cloneable, then the value is stored as a serialized array in a single row in the database.
Multiple thì lưu dạng csv là đúng rồi. Nhưng nếu cloneable thì sẽ vẫn là serialized array e ạ.

2024-08-19 05:33 UTC, tanftw commented on docs/fields/taxonomy-advanced.md
> -If the field is cloneable, then the value is stored as a serialized array in a single row in the database.
Đúng rồi, e update lại docs rồi đó

2024-09-07 05:25 UTC, rilwis approved these changes

2024-09-07 05:25 UTC, merged